#!/bin/sh

set +o errexit +o nounset

test -n "${XTRACE}" && set -o xtrace

set -o errexit -o nounset

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}

if [ -e ${GIT_ROOT}/.version ]; then 
GIT_DESCRIBE=$(cat ${GIT_ROOT}/.version)
GIT_BRANCH="master"
ARTIFACT_NAME="fissile"
fi

GIT_DESCRIBE=${GIT_DESCRIBE:-$(git describe --tags --long)}
GIT_BRANCH=${GIT_BRANCH:-$(git name-rev --name-only HEAD)}
ARTIFACT_NAME=${ARTIFACT_NAME:-$(basename $(git config --get remote.origin.url) .git | sed s/^scf-//)}

GIT_TAG=${GIT_TAG:-$(echo ${GIT_DESCRIBE} | awk -F - '{ print $1 }' )}
GIT_COMMITS=${GIT_COMMITS:-$(echo ${GIT_DESCRIBE} | awk -F - '{ print $2 }' )}
GIT_SHA=${GIT_SHA:-$(echo ${GIT_DESCRIBE} | awk -F - '{ print $3 }' )}

ARTIFACT_VERSION=${GIT_TAG}+${GIT_COMMITS}.${GIT_SHA}

APP_VERSION=${ARTIFACT_NAME}-${ARTIFACT_VERSION}

set +o errexit +o nounset +o xtrace
