#!/bin/sh

GIT_ROOT=${GIT_ROOT:-$(git rev-parse --show-toplevel)}
SRC=`basename $(pwd)`

. ${GIT_ROOT}/make/include/versioning
echo ${ARTIFACT_VERSION} > .version

cd ..
tar --exclude=.git -czvf fissile-${ARTIFACT_VERSION}.tar.gz $SRC 
cd $SRC

#mv $GOPATH/src/github.com/SUSE/fissile-$GIT_TAG-$GIT_COMMITS-$GIT_SHA.tgz .

